version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  reading:
    build: .
    container_name: reading
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - redis
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/reading
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379